# This is a basic workflow that is manually triggered

name: TMB Portfolio Template

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # [push]
  schedule:
      # Runs "at minute 55 past every hour" (see https://crontab.guru)
      - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
